const amenityFilter = {
  targetApiField: "amenities",
  displayName: "Amenities",
  options: [
    { label: "Accessible Amphitheater", value: "accessible-amphitheater" },
    { label: "Accessible Ball Diamond", value: "accessible-ball-diamond" },
    {
      label: "Accessible Community Gardens",
      value: "accessible-community-gardens",
    },
    { label: "Accessible Playgrounds", value: "accessible-playgrounds" },
    { label: "Activity Rooms", value: "activity-rooms" },
    {
      label: "Agricultural Resource Center",
      value: "agricultural-resource-center",
    },
    {
      label: "Amenities Are Pending Construction",
      value: "amenities-are-pending-construction",
    },
    { label: "Amphitheater", value: "amphitheater" },
    { label: "Art Gallery", value: "art-gallery" },
    { label: "Arts Center", value: "arts-center" },
    { label: "Athletic Field", value: "athletic-field" },
    { label: "Athletic Fields", value: "athletic-fields" },
    { label: "Auditorium", value: "auditorium" },
    { label: "Ball Diamonds", value: "ball-diamonds" },
    { label: "Boat Ramps", value: "boat-ramps" },
    { label: "Boat Rentals", value: "boat-rentals" },
    { label: "Community Center", value: "community-center" },
    { label: "Community Gardens", value: "community-gardens" },
    { label: "Computer Lab", value: "computer-lab" },
    { label: "Concert Bandshell", value: "concert-bandshell" },
    { label: "Conference Center", value: "conference-center" },
    { label: "Dog Park", value: "dog-park" },
    { label: "Drones Permitted", value: "drones-permitted" },
    { label: "Exhibits", value: "exhibits" },
    { label: "Farmlands", value: "farmlands" },
    { label: "Fishing Center", value: "fishing-center" },
    { label: "Gazebo", value: "gazebo" },
    { label: "Historic Site", value: "historic-site" },
    { label: "Historical Site", value: "historical-site" },
    { label: "Horseshoe Pits", value: "horseshoe-pits" },
    { label: "Indoor Athletic Fields", value: "indoor-athletic-fields" },
    {
      label: "Indoor Multipurpose Courts",
      value: "indoor-multipurpose-courts",
    },
    {
      label: "Indoor Multi-Purpose Courts",
      value: "indoor-multi-purpose-courts",
    },
    { label: "Indoor Pickleball Courts", value: "indoor-pickleball-courts" },
    { label: "Indoor Pool", value: "indoor-pool" },
    { label: "Indoor Soccer Arena", value: "indoor-soccer-arena" },
    { label: "Indoor Tennis Courts", value: "indoor-tennis-courts" },
    { label: "Indoor Track", value: "indoor-track" },
    { label: "Interpretive Center", value: "interpretive-center" },
    { label: "Interpretive Museum", value: "interpretive-museum" },
    { label: "Lodge", value: "lodge" },
    { label: "Meditative Labyrinth", value: "meditative-labyrinth" },
    { label: "Meeting Rooms", value: "meeting-rooms" },
    { label: "Multipurpose Courts", value: "multipurpose-courts" },
    { label: "Multi-Purpose Courts", value: "multi-purpose-courts" },
    { label: "Museum", value: "museum" },
    { label: "Natural Areas", value: "natural-areas" },
    {
      label: "Natural Rare Wild Bird Habitat",
      value: "natural-rare-wild-bird-habitat",
    },
    { label: "Nature Center", value: "nature-center" },
    { label: "Nature Trails", value: "nature-trails" },
    {
      label: "Outdoor Pickleball Courts",
      value: "outdoor-pickleball-courts",
    },
    { label: "Paved Paths", value: "paved-paths" },
    { label: "Paved Walking Path", value: "paved-walking-path" },
    { label: "Paved Walking Paths", value: "paved-walking-paths" },
    { label: "Pavilion", value: "pavilion" },
    { label: "Pavilions", value: "pavilions" },
    { label: "Picnic Area", value: "picnic-area" },
    { label: "Picnic Areas", value: "picnic-areas" },
    { label: "Pier", value: "pier" },
    { label: "Piers", value: "piers" },
    { label: "Playground", value: "playground" },
    { label: "Playgrounds", value: "playgrounds" },
    {
      label: "Police Athletic League Center",
      value: "police-athletic-league-center",
    },
    { label: "Pond-Lake", value: "pond-lake" },
    {
      label: "Recreation And Parks Office",
      value: "recreation-and-parks-office",
    },
    {
      label: "Recreation And Parks Regional Office",
      value: "recreation-and-parks-regional-office",
    },
    { label: "Reflective Fountain", value: "reflective-fountain" },
    { label: "Restrooms", value: "restrooms" },
    { label: "Restrooms ", value: "restrooms " },
    { label: "Roller Hockey Court", value: "roller-hockey-court" },
    { label: "Sand Volleyball Court", value: "sand-volleyball-court" },
    { label: "Sand Volleyball Courts", value: "sand-volleyball-courts" },
    { label: "Shoreline", value: "shoreline" },
    { label: "Skate Park", value: "skate-park" },
    { label: "Stage", value: "stage" },
    { label: "Swimming", value: "swimming" },
    { label: "Tennis Courts", value: "tennis-courts" },
    {
      label: "Therapeutic Recreation Office",
      value: "therapeutic-recreation-office",
    },
    { label: "Tracks", value: "tracks" },
    { label: "Under Construction", value: "under-construction" },
    {
      label: "Visual And Interactive Meditative Displays ",
      value: "visual-and-interactive meditative-displays ",
    },
  ],
};

export default [amenityFilter];
